library("dplyr")
setwd("E:\course4\household_power_consumption")
ds1 <- read.table("household_power_consumption.txt",header=TRUE, sep=";",na.strings="?")
ds2 <- mutate(ds1, Date1 = as.Date(Date, "%d/%m/%Y"))
ds3<- filter(ds2,Date1>= "2007-02-01" & Date1 <= "2007-02-02")
rm(ls=ds1)
rm(ls=ds2)
hist(ds3$Global_active_power,xlab="Global Active Power (kilowatts",col="red",main="Global Active Power")
dev.copy(png,file="plot1.png")
dev.off()